#!/bin/bash  -x
function ArraySortWithAscending()
{
	for (( i=1;i<=10;i++))
	do
		No=$((RANDOM%1000))
		array[i]=$No
	done
		echo ${array[@]}
	for (( i=1;i<=10;i++))
	do
		for (( j=i+1;j<=10;j++))
		do
			if [[ ${array[i]} -gt ${array[j]} ]]
			then
				temp=${array[i]}
				array[i]=${array[j]}
				array[j]=$temp
			fi
		done
	done
	echo "Array sorting with Ascending order:${array[@]}"
	echo "Second Smallest element in the array:${array[2]}"
	echo "Second largest element in the array:${array[9]}"
}

ArraySortWithAscending
